name: CI/CD Docker + K8s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build and Tag Docker image
        run: |
          TAG=$(date +%s)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          docker build -t jitendrathakur2/node-hello:$TAG .
          docker tag jitendrathakur2/node-hello:$TAG jitendrathakur2/node-hello:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push jitendrathakur2/node-hello:$IMAGE_TAG
          docker push jitendrathakur2/node-hello:latest

      - name: Update Kubernetes Deployment
        run: |
          # Cross-platform compatible sed
          sed -i.bak "s|image: jitendrathakur2/node-hello:.*|image: jitendrathakur2/node-hello:${IMAGE_TAG}|" k8s/deployment.yaml
          rm -f k8s/deployment.yaml.bak

          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/node-hello

      - name: Get Deployment URL
        run: minikube service node-hello --url
